imports:
    - { resource: banker.yml }

parameters:
    locale:            en
    secret:            ThisTokenIsNotSoSecretChangeIt
    knp_paginator.template.pagination: MopaBootstrapBundle:Pagination:sliding.html.twig

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "pdo_sqlite"
        path:     "%kernel.root_dir%/data/data.db3"
        charset:  UTF8
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Mopa configuration
mopa_bootstrap:
    form:
        render_fieldset: false
        show_legend: false
        render_required_asterisk: true
        render_optional_text: false